
version: 2

jobs:
  test:
    docker:
      - image: node

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run: yarn test # Run tests.
      - run: yarn build # Build a production build to check if any warnings come up.
      - run:
          name: Fix ssh Could not resolve hostname
          command: |
            ssh-keyscan 124.109.43.145 >> ~/.ssh/known_hosts # Add live server IP to known hosts.
      - add_ssh_keys: # add private SSH key from CircleCI account based on fingerprint.
          fingerprints:
            - "7c:50:6a:76:d6:1f:bd:ac:1a:9c:99:6d:91:0b:c7:92"      
      - run: ssh ubuntu@124.109.43.145
      - run: node --version
  
  deploy-dev:
    docker:
      - image: node

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      # - run: yarn run deploy

  deploy-production:
    docker:
      - image: node

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      # - run: yarn run deploy

workflows:
  version: 2
  build-and-deploy:
   jobs:
     - test
     - deploy-dev:
         requires:
           - test
         filters:
           branches:
             only: dev
     - deploy-production:
         requires:
           - test
         filters:
           branches:
             only: master